app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin.
  baseUrl: http://localhost:3000
  listen:
    port: 3000
    # Bind to all interfaces (0.0.0.0) for Docker compatibility
    host: 0.0.0.0

backend:
  # Note that the baseUrl should be the URL that the browser and other clients
  # should use when communicating with the backend, i.e. it needs to be
  # reachable not just from within the backend host, but from all of your
  # callers. When its value is "http://localhost:7007", it's strictly private
  # and can't be reached by others.
  baseUrl: http://localhost:7007
  # The listener can also be expressed as a single <host>:<port> string. In this case we bind to
  # all interfaces, the most permissive setting. The right value depends on your specific deployment.
  listen:
    port: 7007
    # Bind to all interfaces (0.0.0.0) for Docker compatibility
    host: 0.0.0.0
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
  cors:
    origin: http://localhost:7007
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true

# will merge with main file, both guest and github will be available
auth:
  # repeat environment from main file
  environment: development
  # now the new provider (will add to main file)
  providers:
    github:
      development:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
            - resolver: emailMatchingUserEntityProfileEmail
            - resolver: emailLocalPartMatchingUserEntityName

catalog:
  locations:
    # Local example data, file locations are relative to the backend process, typically `packages/backend`
    - type: file
      target: /app/examples/entities.yaml
    # Local example template
    - type: file
      target: /app/examples/template/template.yaml
      rules:
        - allow: [Template]
    # Local example organizational data
    - type: file
      target: /app/examples/org.yaml
      rules:
        - allow: [User, Group]  
    # Local example apis
    - type: file
      target: /app/examples/apis.yaml
    # Local example resources
    - type: file
      target: /app/examples/resources.yaml
    # Local example clusters
    - type: file
      target: /app/examples/clusters.yaml

permission:
  rbac:
    policies-csv-file: /app/rbac-policy.csv
