apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: devportal-base
  description: An open source Backstage distro.
  # Example for optional annotations
  annotations:
    github.com/project-slug: veecode-platform/devportal-base
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: andrevtg
  lifecycle: experimental
