
services:
  devportal-base:
    build:
      context: .
      dockerfile: docker/Dockerfile-dev
      target: base  # Use the base stage for development
    container_name: devportal-base-dev
    working_dir: /opt/app
    # we are NOT mounting the entire project for development directly
    # dealing with node_modules and yarn cache volumes is an impossible task
    # volumes:
    #   # Mount the entire project for development
    #   - .:/opt/src
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--no-node-snapshot
    ports:
      # Backend port
      - "7007:7007"
      # Frontend port  
      - "3000:3000"
    # Keep container running for shell access
    tty: true
    stdin_open: true
    # Override default command to keep container alive
    command: sleep infinity
    stop_signal: SIGKILL
    networks:
      - devportal-network

  # Optional: Add a database service for local development
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: devportal-postgres
  #   environment:
  #     POSTGRES_DB: backstage
  #     POSTGRES_USER: backstage
  #     POSTGRES_PASSWORD: backstage
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - devportal-network

volumes:
  # avoid mounting any node_modules or yarn caches
  postgres_data:

networks:
  devportal-network:
    driver: bridge
