#
# Copyright (c) 2025-2026 Vertigo Global LLC and Vertigo Tecnologia.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# This Dockerfile is used for development purposes only.
# It is not intended to be used for production.
# Think of this as a form of building the project without a
# Node installation in the host machine.
#

# We will use an ubi10 Node.js image for VeeCode DevPortal distro
FROM registry.redhat.io/ubi9/nodejs-22:9.6-1757333865 AS base

USER root

RUN dnf install -y \
      python3 make gcc-c++ git pkg-config \
      tar gzip ca-certificates \
    && dnf clean all

USER default

# Enable Yarn via Corepack (Node 22)
RUN npm install -g corepack && corepack enable
