apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
spec:
  type: service
  owner: group:default/backstage-admins
  lifecycle: experimental
  system: examples
