name: Echo Workflow

permissions:
  contents: none

on: workflow_dispatch

jobs:

  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Hello, this is an useless workflow!"
