name: Echo Workflow

permissions:
  contents: none

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to echo'
        required: true
        type: string

jobs:

  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "${{ inputs.message }}"
